#!/bin/sh
if [ "$#" -ne 1 ]; then
echo "please specify release version"
exit 1
fi

rm -rf install
rm -rf build
cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install
cmake --build build
cmake --install build

cd install
mv latest imrad-$1
zip -r imrad-$1-linux64.zip . 

